# Generated by Django 5.2.5 on 2025-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='id_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
