# Generated by Django 5.2.5 on 2025-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_printed',
            field=models.CharField(blank=True, default=[('printed', 'printed'), ('pending', 'pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('wish_list', 'Wish List')], default='pending', max_length=20),
        ),
    ]
