# Generated by Django 5.2.5 on 2025-10-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_order_printed_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.worker'),
        ),
    ]
