# Generated by Django 5.2.5 on 2025-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_order_user_order_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_printed',
            field=models.CharField(blank=True, choices=[('printed', 'printed'), ('pending', 'pending')], max_length=100, null=True),
        ),
    ]
